ft. python-script-runner.yml add check installed packages

diff --git a/.github/workflows/python-script-runner.yml b/.github/workflows/python-script-runner.yml
--- a/.github/workflows/python-script-runner.yml
+++ b/.github/workflows/python-script-runner.yml
@@ -25,6 +25,16 @@ jobs:
         python -m pip install --upgrade pip
         pip install flake8 pytest
         if [ -f script/requirements.txt ]; then pip install -r scripts/requirements.txt; fi
+    - name: Check installed packages
+      run: |
+        pip list > installed_packages.txt
+        if grep -Fxq -f requirements.txt installed_packages.txt
+        then
+          echo "All required packages were installed."
+        else
+          echo "Some required packages were not installed."
+          exit 1
+        fi
     - name: Lint with flake8
       run: |
         # stop the build if there are Python syntax errors or undefined names
