ft ymls adjustments

diff --git a/.github/workflows/script-runner-01.yml b/.github/workflows/script-runner-01.yml
--- a/.github/workflows/script-runner-01.yml
+++ b/.github/workflows/script-runner-01.yml
@@ -40,6 +40,17 @@ jobs:
             echo "requirements.txt not found"; 
           fi
 
+      - name: Check installed packages
+        run: |
+          pip list > scripts/installed_packages.txt
+          if grep -Fxq -f scripts/requirements.txt scripts/installed_packages.txt
+          then
+            echo "All required packages were installed."
+          else
+            echo "Some required packages were not installed."
+            exit 1
+          fi
+
       - name: Check then run ISS tracker
         run: | 
           if [ -f "scripts/iss_tracker.py" ]; then 
